import type { PageName } from './siteState'

export interface SubPageContent {
  lines: string[]
  badges?: string[]
  badgeAnchorLineIndex?: number
}

export const SITE_CONTENT: Record<Exclude<PageName, 'home'>, SubPageContent> = {
  about: {
    lines: [
      '╔══════════════════════════════════════════════════════════════════════════════════════════════════════════════╗',
      '║                                                                                                              ║',
      '║   _______  _______  __    _  _______        ___   _______         _______        ______   _______  __   __   ║',
      '║  |       ||       ||  |  | ||       |      |   | |       |       |   _   |      |      | |       ||  | |  |  ║',
      '║  |____   ||    ___||   |_| ||   _   |      |   | |  _____| ____  |  |_|  |      |  _    ||    ___||  |_|  |  ║',
      '║   ____|  ||   |___ |       ||  | |  |      |   | | |_____ |____| |       |      | | |   ||   |___ |       |  ║',
      '║  | ______||    ___||  _    ||  |_|  | ___  |   | |_____  |       |       | ___  | |_|   ||    ___||       |  ║',
      '║  | |_____ |   |___ | | |   ||       ||   | |   |  _____| |       |   _   ||   | |       ||   |___  |     |   ║',
      '║  |_______||_______||_|  |__||_______||___| |___| |_______|       |__| |__||___| |______| |_______|  |___|    ║',
      '║                                                                                                              ║',
      '║                                                                                                              ║',
      '║  > Hi, I\'m Zeno.                                                                                             ║',
      '║                                                                                                              ║',
      '║    I am a student majoring in Intelligent Science and Technology at Southwest University.                    ║',
      '║    Currently, I am honing my skills in front-end development with the ultimate goal                          ║',
      '║    of becoming a professional Front-end or Full-stack Software Engineer.                                     ║',
      '║                                                                                                              ║',
      '║    I built this website to serve as more than just a digital business card. Like many creators,              ║',
      '║    I wanted a dedicated space to curate my projects and push the boundaries of my potential.                 ║',
      '║                                                                                                              ║',
      '║    Moving forward, I plan to launch a technical blog here to share my insights and journey                   ║',
      '║    through various tech stacks.                                                                              ║',
      '║                                                                                                              ║',
      '╠══════════════════════════════════════════════════════════════════════════════════════════════════════════════╣',
      '║                                                                                                              ║',
      '║  > My tech stacks:                                                                                           ║',
      '║                                                                                                              ║',
      '║                                                                                                              ║',
      '║                                                                                                              ║',
      '║                                                                                                              ║',
      '╚══════════════════════════════════════════════════════════════════════════════════════════════════════════════╝',
    ],
    badges: [
      'https://img.shields.io/badge/TypeScript-3178C6?logo=typescript&logoColor=fff',
      'https://img.shields.io/badge/JavaScript-F7DF1E?logo=javascript&logoColor=000',
      'https://img.shields.io/badge/C-00599C?logo=c&logoColor=white',
      'https://img.shields.io/badge/Java-%23ED8B00.svg?logo=openjdk&logoColor=white',
      'https://img.shields.io/badge/Vue.js-4FC08D?logo=vuedotjs&logoColor=fff',
      'https://img.shields.io/badge/React-%2320232a.svg?logo=react&logoColor=%2361DAFB',
      'https://img.shields.io/badge/Three.js-000?logo=threedotjs&logoColor=fff',
      'https://img.shields.io/badge/WebGL-990000?logo=webgl&logoColor=white',
      'https://img.shields.io/badge/Node.js-6DA55F?logo=node.js&logoColor=white',
      'https://img.shields.io/badge/Next.js-black?logo=next.js&logoColor=white',
    ],
    badgeAnchorLineIndex: 25,
  },
  experience: {
    lines: [
      ' _______  __   __  _______  _______  ______    ___   _______  __    _  _______  _______ ',
      '|       ||  |_|  ||       ||       ||    _ |  |   | |       ||  |  | ||       ||       |',
      '|    ___||       ||    _  ||    ___||   | ||  |   | |    ___||   |_| ||       ||    ___|',
      '|   |___ |       ||   |_| ||   |___ |   |_||_ |   | |   |___ |       ||       ||   |___ ',
      '|    ___| |     | |    ___||    ___||    __  ||   | |    ___||  _    ||      _||    ___|',
      '|   |___ |   _   ||   |    |   |___ |   |  | ||   | |   |___ | | |   ||     |_ |   |___ ',
      '|_______||__| |__||___|    |_______||___|  |_||___| |_______||_|  |__||_______||_______|',
      '',
      '> Placeholder for Experience Page.',
      '',
      '  - Internship 1: ...',
      '  - Internship 2: ...',
      '',
      '  Coming soon!',
    ],
  },
  projects: {
    lines: [
      ' ____   ____   ___      _  _____   ____  _____ ____ ',
      '|  _ \\ |  _ \\ / _ \\    | || ____| / ___||_   _/ ___|',
      '| |_) || |_) | | | | _  | ||  _|   \\___ \\ | | \\___ \\',
      '|  __/ |  _ <| |_| || |_| || |___   ___) || |  ___) |',
      '|_|    |_| \\_\\___/  \\___/ |_____| |____/ |_| |____/ ',
      '',
      '> Placeholder for Projects Page.',
      '',
      '  - Project A: ...',
      '  - Project B: ...',
      '',
      '  Coming soon!',
    ],
  },
  contact: {
    lines: [
      '  ____ ___  _   _ _____  _    ____ _____ ',
      ' / ___/ _ \\| \\ | |_   _|/ \\  / ___|_   _|',
      '| |  | | | |  \\| | | | / _ \\| |     | |  ',
      '| |__| |_| | |\\  | | |/ ___ \\ |___  | |  ',
      ' \\____\\___/|_| \\_| |_/_/   \\_\\____| |_|  ',
      '',
      '> Placeholder for Contact Page.',
      '',
      '  - Email: ...',
      '  - GitHub: ...',
      '',
      '  Coming soon!',
    ],
  },
}
