import type { PageName } from './siteState'

export interface SocialBadge {
  img: string
  action: { type: 'link'; url: string } | { type: 'copy'; text: string }
}

export interface SubPageContent {
  lines: string[]
  badges?: string[]
  badgeAnchorLineIndex?: number
  socialBadges?: SocialBadge[]
  socialBadgeAnchorLineIndex?: number
  /** If true, content will be rendered in a scrollable container */
  scrollable?: boolean
}

export const SITE_CONTENT: Record<Exclude<PageName, 'home'>, SubPageContent> = {
  about: {
    lines: [
      '╔══════════════════════════════════════════════════════════════════════════════════════════════════════════════╗',
      '║                                                                                                              ║',
      '║   _______  _______  __    _  _______        ___   _______         _______        ______   _______  __   __   ║',
      '║  |       ||       ||  |  | ||       |      |   | |       |       |   _   |      |      | |       ||  | |  |  ║',
      '║  |____   ||    ___||   |_| ||   _   |      |   | |  _____| ____  |  |_|  |      |  _    ||    ___||  |_|  |  ║',
      '║   ____|  ||   |___ |       ||  | |  |      |   | | |_____ |____| |       |      | | |   ||   |___ |       |  ║',
      '║  | ______||    ___||  _    ||  |_|  | ___  |   | |_____  |       |       | ___  | |_|   ||    ___||       |  ║',
      '║  | |_____ |   |___ | | |   ||       ||   | |   |  _____| |       |   _   ||   | |       ||   |___  |     |   ║',
      '║  |_______||_______||_|  |__||_______||___| |___| |_______|       |__| |__||___| |______| |_______|  |___|    ║',
      '║                                                                                                              ║',
      '║                                                                                                              ║',
      '║  > Hi, I\'m Zeno.                                                                                             ║',
      '║                                                                                                              ║',
      '║    I am a student majoring in Intelligent Science and Technology at Southwest University.                    ║',
      '║    Currently, I am honing my skills in front-end development with the ultimate goal                          ║',
      '║    of becoming a professional Front-end or Full-stack Software Engineer.                                     ║',
      '║                                                                                                              ║',
      '║    I built this website to serve as more than just a digital business card. Like many creators,              ║',
      '║    I wanted a dedicated space to curate my projects and push the boundaries of my potential.                 ║',
      '║                                                                                                              ║',
      '║    Moving forward, I plan to launch a technical blog here to share my insights and journey                   ║',
      '║    through various tech stacks.                                                                              ║',
      '║                                                                                                              ║',
      '║                                                                                                              ║',
      '║  > My tech stacks:                                                                                           ║',
      '║                                                                                                              ║',
      '║                                                                                                              ║',
      '║                                                                                                              ║',
      '║  > Find me at:                                                                                               ║',
      '║                                                                                                              ║',
      '║                                                                                                              ║',
      '║                                                                                                              ║',
      '╚══════════════════════════════════════════════════════════════════════════════════════════════════════════════╝',
    ],
    badges: [
      'https://img.shields.io/badge/TypeScript-3178C6?logo=typescript&logoColor=fff',
      'https://img.shields.io/badge/JavaScript-F7DF1E?logo=javascript&logoColor=000',
      'https://img.shields.io/badge/C-00599C?logo=c&logoColor=white',
      'https://img.shields.io/badge/Java-%23ED8B00.svg?logo=openjdk&logoColor=white',
      'https://img.shields.io/badge/Vue.js-4FC08D?logo=vuedotjs&logoColor=fff',
      'https://img.shields.io/badge/React-%2320232a.svg?logo=react&logoColor=%2361DAFB',
      'https://img.shields.io/badge/Three.js-000?logo=threedotjs&logoColor=fff',
      'https://img.shields.io/badge/WebGL-990000?logo=webgl&logoColor=white',
      'https://img.shields.io/badge/Node.js-6DA55F?logo=node.js&logoColor=white',
      'https://img.shields.io/badge/Next.js-black?logo=next.js&logoColor=white',
    ],
    badgeAnchorLineIndex: 24,
    socialBadges: [
      { img: 'https://img.shields.io/badge/GitHub-%23121011.svg?logo=github&logoColor=white', action: { type: 'link', url: 'https://github.com/zenojor' } },
      { img: 'https://img.shields.io/badge/Discord-%235865F2.svg?logo=discord&logoColor=white', action: { type: 'copy', text: '1zeno' } },
      { img: 'https://img.shields.io/badge/Bilibili-00A1D6?logo=bilibili&logoColor=fff', action: { type: 'link', url: 'https://space.bilibili.com/23738480?spm_id_from=333.1007.0.0' } },
      { img: 'https://img.shields.io/badge/WeChat-07C160?logo=wechat&logoColor=white', action: { type: 'copy', text: 'zenoknowda' } },
      { img: 'https://img.shields.io/badge/LeetCode-000000?logo=LeetCode&logoColor=%23d16c06', action: { type: 'link', url: 'https://leetcode.cn/u/zeus-13/' } },
      { img: 'https://img.shields.io/badge/WakaTime-000000?logo=wakatime&logoColor=white', action: { type: 'link', url: 'https://wakatime.com/@d7c0fb7f-430a-4bd3-a151-4cc70733f6c7' } },
    ],
    socialBadgeAnchorLineIndex: 28,
  },
  experience: {
    lines: [
      ' _______  __   __  _______  _______  ______    ___   _______  __    _  _______  _______ ',
      '|       ||  |_|  ||       ||       ||    _ |  |   | |       ||  |  | ||       ||       |',
      '|    ___||       ||    _  ||    ___||   | ||  |   | |    ___||   |_| ||       ||    ___|',
      '|   |___ |       ||   |_| ||   |___ |   |_||_ |   | |   |___ |       ||       ||   |___ ',
      '|    ___| |     | |    ___||    ___||    __  ||   | |    ___||  _    ||      _||    ___|',
      '|   |___ |   _   ||   |    |   |___ |   |  | ||   | |   |___ | | |   ||     |_ |   |___ ',
      '|_______||__| |__||___|    |_______||___|  |_||___| |_______||_|  |__||_______||_______|',
      '',
      '> Still looking for an internship!',
    ],
  },
  projects: {
    lines: [
      ' _______  ______    _______      ___  _______  _______  _______  _______ ',
      '|       ||    _ |  |       |    |   ||       ||       ||       ||       |',
      '|    _  ||   | ||  |   _   |    |   ||    ___||       ||_     _||  _____|',
      '|   |_| ||   |_||_ |  | |  |    |   ||   |___ |       |  |   |  | |_____ ',
      '|    ___||    __  ||  |_|  | ___|   ||    ___||      _|  |   |  |_____  |',
      '|   |    |   |  | ||       ||       ||   |___ |     |_   |   |   _____| |',
      '|___|    |___|  |_||_______||_______||_______||_______|  |___|  |_______|',
      '|',
      '> A curated collection of my work.',
      '|',
      '|',
      '  01  Personal Website (This Site)',
      '|',
      '      A fully interactive 3D personal portfolio',
      '      built with Three.js, Vue 3, and custom',
      '      ASCII rendering pipelines. Features include',
      '      dynamic text layout with obstacle avoidance,',
      '      silhouette-based ASCII art generation,',
      '      smooth page transitions with dissolve/materialize',
      '      effects, and responsive design across all',
      '      screen sizes.',
      '|',
      '      Tech: Three.js · Vue 3 · TypeScript · GLSL',
      '      Status: ████████████████████ 100%',
      // '|',
      // '|',
      // '  02  Real-Time Chat Application',
      // '|',
      // '      ----------------------------------------',
      // '      --------------------------------------------',
      // '      --------------------',
      // '      --------------------------------',
      // '      ---------------------------------------------',
      // '      -------------------------------',
      // '|',
      // '      Tech: -------------------------',
      // '      Status: ████████████████░░░░ 80%',
      // '|',
      // '|',
      // '  03  -------------------------------------------',
      // '|',
      // '      --------------------------------',
      // '      -----------------------------------------------',
      // '      --------------------',
      // '      ----------------------',
      // '      --------------------',
      // '      --------------------',
      // '|',
      // '      Tech: Python · FastAPI · OpenAI · GitHub API',
      // '      Status: ██████████░░░░░░░░░░ 50%',
    ],
    scrollable: true,
  },
  contact: {
    lines: [
      ' _______  _______  __    _  _______  _______  _______  _______ ',
      '|       ||       ||  |  | ||       ||   _   ||       ||       |',
      '|       ||   _   ||   |_| ||_     _||  |_|  ||       ||_     _|',
      '|       ||  | |  ||       |  |   |  |       ||       |  |   |  ',
      '|      _||  |_|  ||  _    |  |   |  |       ||      _|  |   |  ',
      '|     |_ |       || | |   |  |   |  |   _   ||     |_   |   |  ',
      '|_______||_______||_|  |__|  |___|  |__| |__||_______|  |___|  ',
      '',
      '> I am still looking for opportunities.',
      '',
      '  If you have any opportunities, feel free to reach out -',
      '  I would be happy to chat with you.',
      '',
      '',
      '> Reach out here:',
      '',
      '',
    ],
    socialBadges: [
      { img: 'https://img.shields.io/badge/GitHub-%23121011.svg?logo=github&logoColor=white', action: { type: 'link', url: 'https://github.com/zenojor' } },
      { img: 'https://img.shields.io/badge/WeChat-07C160?logo=wechat&logoColor=white', action: { type: 'copy', text: 'zenoknowda' } },
      { img: 'https://img.shields.io/badge/Gmail-D14836?logo=gmail&logoColor=white', action: { type: 'link', url: 'mailto:zenoknowda@gmail.com' } },
    ],
    socialBadgeAnchorLineIndex: 14,
  },
}
